
import React, { useState } from 'react'
// Formik
import { useFormik } from "formik";
import * as Yup from "yup";

const CountrySelect = () => {

    const [countries, setCountries] = useState([
      { id: 1, code: "AF", name: "Afghanistan", dialCode: "+93" },
      { id: 2, code: "AL", name: "Albania", dialCode: "+355" },
      { id: 3, code: "DZ", name: "Algeria", dialCode: "+213" },
      { id: 4, code: "AS", name: "American Samoa", dialCode: "+1684" },
      { id: 5, code: "AD", name: "Andorra", dialCode: "+376" },
      { id: 6, code: "AO", name: "Angola", dialCode: "+244" },
      { id: 7, code: "AI", name: "Anguilla", dialCode: "+1264" },
      { id: 8, code: "AQ", name: "Antarctica", dialCode: "" },
      { id: 9, code: "AG", name: "Antigua and Barbuda", dialCode: "+1268" },
      { id: 10, code: "AR", name: "Argentina", dialCode: "+54" },
      { id: 11, code: "AM", name: "Armenia", dialCode: "+374" },
      { id: 12, code: "AW", name: "Aruba", dialCode: "+297" },
      { id: 13, code: "AU", name: "Australia", dialCode: "+61" },
      { id: 14, code: "AT", name: "Austria", dialCode: "+43" },
      { id: 15, code: "AZ", name: "Azerbaijan", dialCode: "+994" },
      { id: 16, code: "BS", name: "Bahamas", dialCode: "+1242" },
      { id: 17, code: "BH", name: "Bahrain", dialCode: "+973" },
      { id: 18, code: "BD", name: "Bangladesh", dialCode: "+880" },
      { id: 19, code: "BB", name: "Barbados", dialCode: "+1246" },
      { id: 20, code: "BY", name: "Belarus", dialCode: "+375" },
      { id: 21, code: "BE", name: "Belgium", dialCode: "+32" },
      { id: 22, code: "BZ", name: "Belize", dialCode: "+501" },
      { id: 23, code: "BJ", name: "Benin", dialCode: "+229" },
      { id: 24, code: "BM", name: "Bermuda", dialCode: "+1441" },
      { id: 25, code: "BT", name: "Bhutan", dialCode: "+975" },
      { id: 26, code: "BO", name: "Bolivia", dialCode: "+591" },
      { id: 27, code: "BA", name: "Bosnia and Herzegovina", dialCode: "+387" },
      { id: 28, code: "BW", name: "Botswana", dialCode: "+267" },
      { id: 29, code: "BV", name: "Bouvet Island", dialCode: "" },
      { id: 30, code: "BR", name: "Brazil", dialCode: "+55" },
      { id: 31, code: "IO", name: "British Indian Ocean Territory", dialCode: "" },
      { id: 32, code: "BN", name: "Brunei Darussalam", dialCode: "+673" },
      { id: 33, code: "BG", name: "Bulgaria", dialCode: "+359" },
      { id: 34, code: "BF", name: "Burkina Faso", dialCode: "+226" },
      { id: 35, code: "BI", name: "Burundi", dialCode: "+257" },
      { id: 36, code: "KH", name: "Cambodia", dialCode: "+855" },
      { id: 37, code: "CM", name: "Cameroon", dialCode: "+237" },
      { id: 38, code: "CA", name: "Canada", dialCode: "+1" },
      { id: 39, code: "CV", name: "Cape Verde", dialCode: "+238" },
      { id: 40, code: "KY", name: "Cayman Islands", dialCode: "+1345" },
      { id: 41, code: "CF", name: "Central African Republic", dialCode: "+236" },
      { id: 42, code: "TD", name: "Chad", dialCode: "+235" },
      { id: 43, code: "CL", name: "Chile", dialCode: "+56" },
      { id: 44, code: "CN", name: "China", dialCode: "+86" },
      { id: 45, code: "CX", name: "Christmas Island", dialCode: "" },
      { id: 46, code: "CC", name: "Cocos (Keeling) Islands", dialCode: "" },
      { id: 47, code: "CO", name: "Colombia", dialCode: "+57" },
      { id: 48, code: "KM", name: "Comoros", dialCode: "+269" },
      { id: 49, code: "CG", name: "Congo", dialCode: "+242" },
      {
        id: 50,
        code: "CD",
        name: "Congo, the Democratic Republic of the",
        dialCode: "+242",
      },
      { id: 51, code: "CK", name: "Cook Islands", dialCode: "+682" },
      { id: 52, code: "CR", name: "Costa Rica", dialCode: "+506" },
      { id: 53, code: "CI", name: "Cote DIvoire", dialCode: "+225" },
      { id: 54, code: "HR", name: "Croatia", dialCode: "+385" },
      { id: 55, code: "CU", name: "Cuba", dialCode: "+53" },
      { id: 56, code: "CY", name: "Cyprus", dialCode: "+357" },
      { id: 57, code: "CZ", name: "Czech Republic", dialCode: "+420" },
      { id: 58, code: "DK", name: "Denmark", dialCode: "+45" },
      { id: 59, code: "DJ", name: "Djibouti", dialCode: "+253" },
      { id: 60, code: "DM", name: "Dominica", dialCode: "+1767" },
      { id: 61, code: "DO", name: "Dominican Republic", dialCode: "+1809" },
      { id: 62, code: "EC", name: "Ecuador", dialCode: "+593" },
      { id: 63, code: "EG", name: "Egypt", dialCode: "+20" },
      { id: 64, code: "SV", name: "El Salvador", dialCode: "+503" },
      { id: 65, code: "GQ", name: "Equatorial Guinea", dialCode: "+240" },
      { id: 66, code: "ER", name: "Eritrea", dialCode: "+291" },
      { id: 67, code: "EE", name: "Estonia", dialCode: "+372" },
      { id: 68, code: "ET", name: "Ethiopia", dialCode: "+251" },
      { id: 69, code: "FK", name: "Falkland Islands (Malvinas)", dialCode: "+500" },
      { id: 70, code: "FO", name: "Faroe Islands", dialCode: "+298" },
      { id: 71, code: "FJ", name: "Fiji", dialCode: "+679" },
      { id: 72, code: "FI", name: "Finland", dialCode: "+358" },
      { id: 73, code: "FR", name: "France", dialCode: "+33" },
      { id: 74, code: "GF", name: "French Guiana", dialCode: "+594" },
      { id: 75, code: "PF", name: "French Polynesia", dialCode: "+689" },
      { id: 76, code: "TF", name: "French Southern Territories", dialCode: "" },
      { id: 77, code: "GA", name: "Gabon", dialCode: "+241" },
      { id: 78, code: "GM", name: "Gambia", dialCode: "+220" },
      { id: 79, code: "GE", name: "Georgia", dialCode: "+995" },
      { id: 80, code: "DE", name: "Germany", dialCode: "+49" },
      { id: 81, code: "GH", name: "Ghana", dialCode: "+233" },
      { id: 82, code: "GI", name: "Gibraltar", dialCode: "+350" },
      { id: 83, code: "GR", name: "Greece", dialCode: "+30" },
      { id: 84, code: "GL", name: "Greenland", dialCode: "+299" },
      { id: 85, code: "GD", name: "Grenada", dialCode: "+1473" },
      { id: 86, code: "GP", name: "Guadeloupe", dialCode: "+590" },
      { id: 87, code: "GU", name: "Guam", dialCode: "+1671" },
      { id: 88, code: "GT", name: "Guatemala", dialCode: "+502" },
      { id: 89, code: "GN", name: "Guinea", dialCode: "+224" },
      { id: 90, code: "GW", name: "Guinea-Bissau", dialCode: "+245" },
      { id: 91, code: "GY", name: "Guyana", dialCode: "+592" },
      { id: 92, code: "HT", name: "Haiti", dialCode: "+509" },
      {
        id: 93,
        code: "HM",
        name: "Heard Island and Mcdonald Islands",
        dialCode: "",
      },
      {
        id: 94,
        code: "VA",
        name: "Holy See (Vatican City State)",
        dialCode: "+39",
      },
      { id: 95, code: "HN", name: "Honduras", dialCode: "+504" },
      { id: 96, code: "HK", name: "Hong Kong", dialCode: "+852" },
      { id: 97, code: "HU", name: "Hungary", dialCode: "+36" },
      { id: 98, code: "IS", name: "Iceland", dialCode: "+354" },
      { id: 99, code: "IN", name: "India", dialCode: "+91" },
      { id: 100, code: "ID", name: "Indonesia", dialCode: "+62" },
      { id: 101, code: "IR", name: "Iran, Islamic Republic of", dialCode: "+98" },
      { id: 102, name: "IRAQ", fullName: "Iraq", code: 368, dialCode: 964 },
      { id: 103, name: "IRELAND", fullName: "Ireland", code: 372, dialCode: 353 },
      { id: 104, name: "ISRAEL", fullName: "Israel", code: 376, dialCode: 972 },
      { id: 105, name: "ITALY", fullName: "Italy", code: 380, dialCode: 39 },
      { id: 106, name: "JAMAICA", fullName: "Jamaica", code: 388, dialCode: 1876 },
      { id: 107, name: "JAPAN", fullName: "Japan", code: 392, dialCode: 81 },
      { id: 108, name: "JORDAN", fullName: "Jordan", code: 400, dialCode: 962 },
      {
        id: 109,
        name: "KAZAKHSTAN",
        fullName: "Kazakhstan",
        code: 398,
        dialCode: 7,
      },
      { id: 110, name: "KENYA", fullName: "Kenya", code: 404, dialCode: 254 },
      { id: 111, name: "KIRIBATI", fullName: "Kiribati", code: 296, dialCode: 686 },
      {
        id: 112,
        name: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
        fullName: "Korea, Democratic People's Republic of",
        code: 408,
        dialCode: 850,
      },
      {
        id: 113,
        name: "KOREA, REPUBLIC OF",
        fullName: "Korea, Republic of",
        code: 410,
        dialCode: 82,
      },
      { id: 114, name: "KUWAIT", fullName: "Kuwait", code: 414, dialCode: 965 },
      {
        id: 115,
        name: "KYRGYZSTAN",
        fullName: "Kyrgyzstan",
        code: 417,
        dialCode: 996,
      },
      {
        id: 116,
        name: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
        fullName: "Lao People's Democratic Republic",
        code: 418,
        dialCode: 856,
      },
      { id: 117, name: "LATVIA", fullName: "Latvia", code: 428, dialCode: 371 },
      { id: 118, name: "LEBANON", fullName: "Lebanon", code: 422, dialCode: 961 },
      { id: 119, name: "LESOTHO", fullName: "Lesotho", code: 426, dialCode: 266 },
      { id: 120, name: "LIBERIA", fullName: "Liberia", code: 430, dialCode: 231 },
      {
        id: 121,
        name: "LIBYAN ARAB JAMAHIRIYA",
        fullName: "Libyan Arab Jamahiriya",
        code: 434,
        dialCode: 218,
      },
      {
        id: 122,
        name: "LIECHTENSTEIN",
        fullName: "Liechtenstein",
        code: 438,
        dialCode: 423,
      },
      {
        id: 123,
        name: "LITHUANIA",
        fullName: "Lithuania",
        code: 440,
        dialCode: 370,
      },
      {
        id: 124,
        name: "LUXEMBOURG",
        fullName: "Luxembourg",
        code: 442,
        dialCode: 352,
      },
      { id: 125, name: "MACAO", fullName: "Macao", code: 446, dialCode: 853 },
      {
        id: 126,
        name: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
        fullName: "Macedonia, the Former Yugoslav Republic of",
        code: 807,
        dialCode: 389,
      },
      {
        id: 127,
        name: "MADAGASCAR",
        fullName: "Madagascar",
        code: 450,
        dialCode: 261,
      },
      { id: 128, name: "MALAWI", fullName: "Malawi", code: 454, dialCode: 265 },
      { id: 129, name: "MALAYSIA", fullName: "Malaysia", code: 458, dialCode: 60 },
      { id: 130, name: "MALDIVES", fullName: "Maldives", code: 462, dialCode: 960 },
      { id: 131, name: "MALI", fullName: "Mali", code: 466, dialCode: 223 },
      { id: 132, name: "MALTA", fullName: "Malta", code: 470, dialCode: 356 },
      {
        id: 133,
        name: "MARSHALL ISLANDS",
        fullName: "Marshall Islands",
        code: 584,
        dialCode: 692,
      },
      {
        id: 134,
        name: "MARTINIQUE",
        fullName: "Martinique",
        code: 474,
        dialCode: 596,
      },
      {
        id: 135,
        name: "MAURITANIA",
        fullName: "Mauritania",
        code: 478,
        dialCode: 222,
      },
      {
        id: 136,
        name: "MAURITIUS",
        fullName: "Mauritius",
        code: 480,
        dialCode: 230,
      },
      { id: 137, name: "MAYOTTE", fullName: "Mayotte", code: null, dialCode: 269 },
      { id: 138, name: "MEXICO", fullName: "Mexico", code: 484, dialCode: 52 },
      {
        id: 139,
        name: "MICRONESIA, FEDERATED STATES OF",
        fullName: "Micronesia, Federated States of",
        code: 583,
        dialCode: 691,
      },
      {
        id: 140,
        name: "MOLDOVA, REPUBLIC OF",
        fullName: "Moldova, Republic of",
        code: 498,
        dialCode: 373,
      },
      { id: 141, name: "MONACO", fullName: "Monaco", code: 492, dialCode: 377 },
      { id: 142, name: "MONGOLIA", fullName: "Mongolia", code: 496, dialCode: 976 },
      {
        id: 143,
        name: "MONTSERRAT",
        fullName: "Montserrat",
        code: 500,
        dialCode: 1664,
      },
      { id: 144, name: "MOROCCO", fullName: "Morocco", code: 504, dialCode: 212 },
      {
        id: 145,
        name: "MOZAMBIQUE",
        fullName: "Mozambique",
        code: 508,
        dialCode: 258,
      },
      { id: 146, name: "MYANMAR", fullName: "Myanmar", code: 104, dialCode: 95 },
      { id: 147, name: "NAMIBIA", fullName: "Namibia", code: 516, dialCode: 264 },
      { id: 148, name: "NAURU", fullName: "Nauru", code: 520, dialCode: 674 },
      { id: 149, name: "NEPAL", fullName: "Nepal", code: 524, dialCode: 977 },
      {
        id: 150,
        name: "NETHERLANDS",
        fullName: "Netherlands",
        code: 528,
        dialCode: 31,
      },
      {
        id: 151,
        name: "NETHERLANDS ANTILLES",
        fullName: "Netherlands Antilles",
        code: 530,
        dialCode: 599,
      },
      {
        id: 152,
        name: "NEW CALEDONIA",
        fullName: "New Caledonia",
        code: 540,
        dialCode: 687,
      },
      {
        id: 153,
        name: "NEW ZEALAND",
        fullName: "New Zealand",
        code: 554,
        dialCode: 64,
      },
      {
        id: 154,
        name: "NICARAGUA",
        fullName: "Nicaragua",
        code: 558,
        dialCode: 505,
      },
      { id: 155, name: "NIGER", fullName: "Niger", code: 562, dialCode: 227 },
      { id: 156, name: "NIGERIA", fullName: "Nigeria", code: 566, dialCode: 234 },
      { id: 157, name: "NIUE", fullName: "Niue", code: 570, dialCode: 683 },
      {
        id: 158,
        name: "NORFOLK ISLAND",
        fullName: "Norfolk Island",
        code: 574,
        dialCode: 672,
      },
      {
        id: 159,
        name: "NORTHERN MARIANA ISLANDS",
        fullName: "Northern Mariana Islands",
        code: 580,
        dialCode: 1670,
      },
      { id: 160, name: "NORWAY", fullName: "Norway", code: 578, dialCode: 47 },
      { id: 161, name: "OMAN", fullName: "Oman", code: 512, dialCode: 968 },
      { id: 162, name: "PAKISTAN", fullName: "Pakistan", code: 586, dialCode: 92 },
      { id: 163, name: "PALAU", fullName: "Palau", code: 585, dialCode: 680 },
      {
        id: 164,
        name: "PALESTINIAN TERRITORY, OCCUPIED",
        fullName: "Palestinian Territory, Occupied",
        code: null,
        dialCode: 970,
      },
      { id: 165, name: "PANAMA", fullName: "Panama", code: 591, dialCode: 507 },
      {
        id: 166,
        name: "PAPUA NEW GUINEA",
        fullName: "Papua New Guinea",
        code: 598,
        dialCode: 675,
      },
      { id: 167, name: "PARAGUAY", fullName: "Paraguay", code: 600, dialCode: 595 },
      { id: 168, name: "PERU", fullName: "Peru", code: 604, dialCode: 51 },
      {
        id: 169,
        name: "PHILIPPINES",
        fullName: "Philippines",
        code: 608,
        dialCode: 63,
      },
      { id: 170, name: "PITCAIRN", fullName: "Pitcairn", code: 612, dialCode: 0 },
      { id: 171, name: "POLAND", fullName: "Poland", code: 616, dialCode: 48 },
      { id: 172, name: "PORTUGAL", fullName: "Portugal", code: 620, dialCode: 351 },
      {
        id: 173,
        name: "PUERTO RICO",
        fullName: "Puerto Rico",
        code: 630,
        dialCode: 1787,
      },
      { id: 174, name: "QATAR", fullName: "Qatar", code: 634, dialCode: 974 },
      { id: 175, name: "REUNION", fullName: "Reunion", code: 638, dialCode: 262 },
      { id: 176, name: "ROMANIA", fullName: "Romania", code: 642, dialCode: 40 },
      {
        id: 177,
        name: "RUSSIAN FEDERATION",
        fullName: "Russian Federation",
        code: 643,
        dialCode: 70,
      },
      { id: 178, name: "RWANDA", fullName: "Rwanda", code: 646, dialCode: 250 },
      {
        id: 179,
        name: "SAINT HELENA",
        fullName: "Saint Helena",
        code: 654,
        dialCode: 290,
      },
      {
        id: 180,
        name: "SAINT KITTS AND NEVIS",
        fullName: "Saint Kitts and Nevis",
        code: 659,
        dialCode: 1869,
      },
      {
        id: 181,
        name: "SAINT LUCIA",
        fullName: "Saint Lucia",
        code: 662,
        dialCode: 1758,
      },
      {
        id: 182,
        name: "SAINT PIERRE AND MIQUELON",
        fullName: "Saint Pierre and Miquelon",
        code: 666,
        dialCode: 508,
      },
      {
        id: 183,
        name: "SAINT VINCENT AND THE GRENADINES",
        fullName: "Saint Vincent and the Grenadines",
        code: 670,
        dialCode: 1784,
      },
      { id: 184, name: "SAMOA", fullName: "Samoa", code: 882, dialCode: 684 },
      {
        id: 185,
        name: "SAN MARINO",
        fullName: "San Marino",
        code: 674,
        dialCode: 378,
      },
      {
        id: 186,
        name: "SAO TOME AND PRINCIPE",
        fullName: "Sao Tome and Principe",
        code: 678,
        dialCode: 239,
      },
      {
        id: 187,
        name: "SAUDI ARABIA",
        fullName: "Saudi Arabia",
        code: 682,
        dialCode: 966,
      },
      { id: 188, name: "SENEGAL", fullName: "Senegal", code: 686, dialCode: 221 },
      {
        id: 189,
        name: "SERBIA AND MONTENEGRO",
        fullName: "Serbia and Montenegro",
        code: null,
        dialCode: 381,
      },
      {
        id: 190,
        name: "SEYCHELLES",
        fullName: "Seychelles",
        code: 690,
        dialCode: 248,
      },
      {
        id: 191,
        name: "SIERRA LEONE",
        displayName: "Sierra Leone",
        isoNumeric: 694,
        dialCode: 232,
      },
      {
        id: 192,
        name: "SINGAPORE",
        displayName: "Singapore",
        isoNumeric: 702,
        dialCode: 65,
      },
      {
        id: 193,
        name: "SLOVAKIA",
        displayName: "Slovakia",
        isoNumeric: 703,
        dialCode: 421,
      },
      {
        id: 194,
        name: "SLOVENIA",
        displayName: "Slovenia",
        isoNumeric: 705,
        dialCode: 386,
      },
      {
        id: 195,
        name: "SOLOMON ISLANDS",
        displayName: "Solomon Islands",
        isoNumeric: 90,
        dialCode: 677,
      },
      {
        id: 196,
        name: "SOMALIA",
        displayName: "Somalia",
        isoNumeric: 706,
        dialCode: 252,
      },
      {
        id: 197,
        name: "SOUTH AFRICA",
        displayName: "South Africa",
        isoNumeric: 710,
        dialCode: 27,
      },
      {
        id: 198,
        name: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
        displayName: "South Georgia and the South Sandwich Islands",
        isoNumeric: null,
        dialCode: 0,
      },
      {
        id: 199,
        name: "SPAIN",
        displayName: "Spain",
        isoNumeric: 724,
        dialCode: 34,
      },
      {
        id: 200,
        name: "SRI LANKA",
        displayName: "Sri Lanka",
        isoNumeric: 144,
        dialCode: 94,
      },
      {
        id: 201,
        name: "SUDAN",
        displayName: "Sudan",
        isoNumeric: 736,
        dialCode: 249,
      },
      {
        id: 202,
        name: "SURINAME",
        displayName: "Suriname",
        isoNumeric: 740,
        dialCode: 597,
      },
      {
        id: 203,
        name: "SVALBARD AND JAN MAYEN",
        displayName: "Svalbard and Jan Mayen",
        isoNumeric: 744,
        dialCode: 47,
      },
      {
        id: 204,
        name: "SWAZILAND",
        displayName: "Swaziland",
        isoNumeric: 748,
        dialCode: 268,
      },
      {
        id: 205,
        name: "SWEDEN",
        displayName: "Sweden",
        isoNumeric: 752,
        dialCode: 46,
      },
      {
        id: 206,
        name: "SWITZERLAND",
        displayName: "Switzerland",
        isoNumeric: 756,
        dialCode: 41,
      },
      {
        id: 207,
        name: "SYRIAN ARAB REPUBLIC",
        displayName: "Syrian Arab Republic",
        isoNumeric: 760,
        dialCode: 963,
      },
      {
        id: 208,
        name: "TAIWAN, PROVINCE OF CHINA",
        displayName: "Taiwan, Province of China",
        isoNumeric: 158,
        dialCode: 886,
      },
      {
        id: 209,
        name: "TAJIKISTAN",
        displayName: "Tajikistan",
        isoNumeric: 762,
        dialCode: 992,
      },
      {
        id: 210,
        name: "TANZANIA, UNITED REPUBLIC OF",
        displayName: "Tanzania, United Republic of",
        isoNumeric: 834,
        dialCode: 255,
      },
      {
        id: 211,
        name: "THAILAND",
        displayName: "Thailand",
        isoNumeric: 764,
        dialCode: 66,
      },
      {
        id: 212,
        name: "TIMOR-LESTE",
        displayName: "Timor-Leste",
        isoNumeric: null,
        dialCode: 670,
      },
      {
        id: 213,
        name: "TOGO",
        displayName: "Togo",
        isoNumeric: 768,
        dialCode: 228,
      },
      {
        id: 214,
        name: "TOKELAU",
        displayName: "Tokelau",
        isoNumeric: 772,
        dialCode: 690,
      },
      {
        id: 215,
        name: "TONGA",
        displayName: "Tonga",
        isoNumeric: 776,
        dialCode: 676,
      },
      {
        id: 216,
        name: "TRINIDAD AND TOBAGO",
        displayName: "Trinidad and Tobago",
        isoNumeric: 780,
        dialCode: 1868,
      },
      {
        id: 217,
        name: "TUNISIA",
        displayName: "Tunisia",
        isoNumeric: 788,
        dialCode: 216,
      },
      {
        id: 218,
        name: "TURKEY",
        displayName: "Turkey",
        isoNumeric: 792,
        dialCode: 90,
      },
      {
        id: 219,
        name: "TURKMENISTAN",
        displayName: "Turkmenistan",
        isoNumeric: 795,
        dialCode: 7370,
      },
      {
        id: 220,
        name: "TURKS AND CAICOS ISLANDS",
        displayName: "Turks and Caicos Islands",
        isoNumeric: 796,
        dialCode: 1649,
      },
      {
        id: 221,
        name: "TUVALU",
        displayName: "Tuvalu",
        isoNumeric: 798,
        dialCode: 688,
      },
      {
        id: 222,
        name: "UGANDA",
        displayName: "Uganda",
        isoNumeric: 800,
        dialCode: 256,
      },
      {
        id: 223,
        name: "UKRAINE",
        displayName: "Ukraine",
        isoNumeric: 804,
        dialCode: 380,
      },
      {
        id: 224,
        name: "UNITED ARAB EMIRATES",
        displayName: "United Arab Emirates",
        isoNumeric: 784,
        dialCode: 971,
      },
      {
        id: 225,
        name: "UNITED KINGDOM",
        displayName: "United Kingdom",
        isoNumeric: 826,
        dialCode: 44,
      },
      {
        id: 226,
        name: "UNITED STATES",
        displayName: "United States",
        isoNumeric: 840,
        dialCode: 1,
      },
      {
        id: 227,
        name: "UNITED STATES MINOR OUTLYING ISLANDS",
        displayName: "United States Minor Outlying Islands",
        isoNumeric: null,
        dialCode: 1,
      },
      {
        id: 228,
        name: "URUGUAY",
        displayName: "Uruguay",
        isoNumeric: 858,
        dialCode: 598,
      },
      {
        id: 229,
        name: "UZBEKISTAN",
        displayName: "Uzbekistan",
        isoNumeric: 860,
        dialCode: 998,
      },
      {
        id: 230,
        name: "VANUATU",
        displayName: "Vanuatu",
        isoNumeric: 548,
        dialCode: 678,
      },
      {
        id: 231,
        name: "VENEZUELA",
        displayName: "Venezuela",
        isoNumeric: 862,
        dialCode: 58,
      },
      {
        id: 232,
        name: "VIET NAM",
        displayName: "Viet Nam",
        isoNumeric: 704,
        dialCode: 84,
      },
      {
        id: 233,
        name: "VIRGIN ISLANDS, BRITISH",
        displayName: "Virgin Islands, British",
        isoNumeric: 92,
        dialCode: 1284,
      },
      {
        id: 234,
        name: "VIRGIN ISLANDS, U.S.",
        displayName: "Virgin Islands, U.s.",
        isoNumeric: 850,
        dialCode: 1340,
      },
      {
        id: 235,
        name: "WALLIS AND FUTUNA",
        displayName: "Wallis and Futuna",
        isoNumeric: 876,
        dialCode: 681,
      },
      {
        id: 236,
        name: "WESTERN SAHARA",
        displayName: "Western Sahara",
        isoNumeric: 732,
        dialCode: 212,
      },
      {
        id: 237,
        name: "YEMEN",
        displayName: "Yemen",
        isoNumeric: 887,
        dialCode: 967,
      },
      {
        id: 238,
        name: "ZAMBIA",
        displayName: "Zambia",
        isoNumeric: 894,
        dialCode: 260,
      },
      {
        id: 239,
        name: "ZIMBABWE",
        displayName: "Zimbabwe",
        isoNumeric: 716,
        dialCode: 263,
      },
    ]);

  return (
    <select onChange={(e) => onSelect(e.target.value)} className="w-20 border border-gray-300 p-2 rounded-l-md focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-500" name="countryCode"
    >
      <option value="">Select Country</option>
      {countries.map((country) => (
        <option key={country.id} value={country.code}>
          {country.dialCode}
        </option>
      ))}
    </select>
  )
}

export default CountrySelect
